name: the_wallet
description: A new Flutter project.

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.2.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  barcode_scan: ^1.0.0
  barcode_flutter: ^1.0.1
  provider: ^3.1.0
  uuid: ^2.0.2
  flutter_speed_dial: ^1.2.1
  shared_preferences: ^0.5.3+4
  sqflite: ^1.1.6+4
  path_provider: ^1.2.0
  image_picker: ^0.6.1+4
  image_cropper: ^1.0.2

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^0.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter

# For information on the generic Dart part of this file, see the
# following page: https://www.dartlang.org/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:
  uses-material-design: true
  assets:
    - assets/img/key.png
  fonts:
    - family: rokkitt
      fonts:
        - asset: assets/fonts/Rokkitt-Medium.ttf
        - asset: assets/fonts/Rokkitt-Bold.ttf
          weight: 700
        - asset: assets/fonts/Rokkitt-Thin.ttf
          weight: 300
